import { Metadata } from "next";
import Contact from "./components/contact";
import Features from "./components/features";
import Hero from "./components/hero";

export const metadata: Metadata = {
  title: {
    template: 'サービスについて',
    default: 'Generated by create next app',
  },
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <Hero />
      <Features />
      <Contact />
    </div>
  )
}