import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/node-toggle";

const inter = Inter({ subsets: ["latin"] });

const navItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const metadata: Metadata = {
  title: {
    template: '%s | Next.js + Tailwind CSS',
    default: 'Next.js + Tailwind CSS',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={cn(inter.className, "min-h-dvh flex flex-col")}>
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="container h-16 flex items-center border-b justify-between">
            <h1 className="font-bold">LOGO</h1>
            <ul className="flex gap-4">
              {navItems.map((item) => (
                <li key={item.label}>
                  <Button variant="ghost" asChild>
                    <Link href={item.href}>{item.label}</Link>
                  </Button>
                </li>
              ))}
            </ul>
          </header>

          <main>{children}</main>

          <footer className="container sticky top-full h-16 flex justify-between items-center border-t">
            <p>&copy; ryusei</p>

            <ModeToggle />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
